---
title: "BaseballSavant"
format: html
---

```{r}
library(tidyverse)
library(mgcv)
library(purrr)
library(lubridate)
library(zoo)
```

Load in Data
```{r}
KCLyakkertechData <- read_csv("KCLYakkertechData.csv")
BeltersyakkertechData <- read_csv("BeltersHitterYakkertechData.csv")
```


Function to calculate advanced hitting stats
```{r}
getAdvancedHitting <- function(df, name){
  df <- df |> 
    filter(Batter == name)
  
  avgExitVelo <- df |> 
    filter(!is.na(ExitSpeed)) |> 
    summarize(avgExitVelo = mean(ExitSpeed)) |> 
    pull(avgExitVelo)
  
  maxExitVelo <- df |> 
    filter(!is.na(ExitSpeed)) |> 
    summarize(max = if (n()==0) NA_real_ else max(ExitSpeed)) |> 
    pull(max)
  
  LASweetSpot <- df |> 
    filter(!is.na(Angle)) |> 
    summarize(pct = mean(Angle >= 8 & Angle <= 32)) |> 
    pull(pct)
  
  hardHitPct <- df |> 
    filter(!is.na(ExitSpeed)) |> 
    summarize(pct = mean(ExitSpeed >= 90)) |> 
    pull(pct)
  
  squaredUpPct <- df |> 
    filter(!is.na(Angle) & !is.na(ExitSpeed)) |> 
    summarize(pct = mean(Angle >= 8 & Angle <= 32 & ExitSpeed >= 90)) |> 
    pull(pct)
  
  kPct <- df |> 
    filter(!is.na(PlayResult) | !is.na(KorBB) | PitchCall == "HitByPitch") |> 
    summarize(
      pct = {
        total_PA <- n()
        strikeouts <- sum(
          PlayResult %in% c("StrikeoutLooking", "StrikeoutSwinging"), na.rm = TRUE
        )
      if(total_PA == 0) 0 else strikeouts / total_PA
      }
    ) |> 
    pull(pct)
  
  bbPct <- df |> 
    filter(!is.na(PlayResult) | !is.na(KorBB)) |>
    summarize(pct = sum(KorBB == "Walk", na.rm = TRUE) / n()) |> 
    pull(pct)
  
  whiffPct <- df |> 
    filter(!is.na(PitchCall)) |> 
    filter(IsSwing == TRUE) |> 
    summarize(pct = mean(PitchCall == "StrikeSwinging")) |> 
    pull(pct)
  
  chasePct <- df |> 
    filter(IsStrike == FALSE) |> 
    filter(!is.na(PitchCall)) |> 
    summarize(pct = mean(IsSwing == TRUE)) |> 
    pull(pct)
  
  xBA <- df |> 
    filter(!is.na(PlayResult)) |> 
    filter(PlayResult != "Walk" & PlayResult != "HitByPitch") |> 
    filter(!(PlayResult %in% c("Single", "Double", "Triple", "HomeRun", "Out", "Error") & is.na(Angle) & is.na(ExitSpeed))) |>  
    summarize(avg = mean(predicted_xba)) |> 
    pull(avg)
  
  xSLG <- df |> 
    filter(!is.na(PlayResult)) |> 
    filter(PlayResult != "Walk" & PlayResult != "HitByPitch") |> 
    filter(!(PlayResult %in% c("Single", "Double", "Triple", "HomeRun", "Out", "Error") & is.na(Angle) & is.na(ExitSpeed))) |> 
    summarize(avg = mean(predicted_xslg)) |> 
    pull(avg)
  
  xWOBA <- df |> 
    filter(!is.na(PlayResult)) |> 
    filter(!(PlayResult %in% c("Single", "Double", "Triple", "HomeRun", "Out", "Error") & is.na(Angle) & is.na(ExitSpeed))) |> 
    summarize(avg = mean(predicted_xwoba)) |> 
    pull(avg)
  
  xBABIP <- df |> 
    filter(predicted_xba > 0) |> 
    summarize(avg = mean(predicted_xba)) |> 
    pull(avg)
  
  babip <- df |> 
    filter(PitchCall == "InPlay" & !is.na(PlayResult)) |> 
    filter(PlayResult != "Walk" & PlayResult != "HitByPitch") |> 
    summarize(avg = sum(PlayResult %in% c("Single","Double","Triple","HomeRun")) / n()) |> 
    pull(avg)
  
  return(
    list(
      avgExitVelo = avgExitVelo,
      maxExitVelo = maxExitVelo,
      LASweetSpot = LASweetSpot,
      hardHitPct = hardHitPct,
      squaredUpPct = squaredUpPct,
      kPct = kPct,
      bbPct = bbPct,
      whiffPct = whiffPct,
      chasePct = chasePct,
      xBA = xBA,
      xSLG = xSLG,
      xWOBA = xWOBA,
      xBABIP = xBABIP,
      babip = babip
    )
  )
    
}

```

Creating Batter Advanced Stats Dataframe
```{r}
kcl_batter_list <- split(KCLyakkertechData, KCLyakkertechData$Batter)

kcl_advanced_by_batter <- map2_df(
  .x = kcl_batter_list,
  .y = names(kcl_batter_list),
  ~ as_tibble(getAdvancedHitting(.x, .y)),
  .id = "Batter"
)

belters_batter_list <- split(BeltersyakkertechData, BeltersyakkertechData$Batter)

belters_advanced_by_batter <- map2_df(
  .x = belters_batter_list,
  .y = names(belters_batter_list),
  ~ as_tibble(getAdvancedHitting(.x, .y)),
  .id = "Batter"
)

invert_cols <- c("kPct", "whiffPct", "chasePct")

#Create Percentile Columns
kcl_advanced_by_batter <- kcl_advanced_by_batter |> 
  mutate(
    across(
      .cols = where(is.numeric) & !all_of(invert_cols),
      .fns  = ~ percent_rank(.) * 100,
      .names = "{.col}_pct"
    )
  ) |> 
  mutate(
    across(
      .cols = all_of(invert_cols),
      .fns  = ~ percent_rank(-.) * 100,
      .names = "{.col}_pct"
    )
  )

belters_advanced_by_batter <- belters_advanced_by_batter |> 
  mutate(
    across(
      .cols = where(is.numeric) & !all_of(invert_cols),
      .fns  = ~ percent_rank(.) * 100,
      .names = "{.col}_pct"
    )
  ) |> 
  mutate(
    across(
      .cols = all_of(invert_cols),
      .fns  = ~ percent_rank(-.) * 100,
      .names = "{.col}_pct"
    )
  )

```

Attach basic hitting stats to advanced stats
```{r}
kcl_basicHitting_files <- c(
  "KCLStats/bluecapsStatsFinal.csv",
  "KCLStats/bobcatsStatsFinal.csv",
  "KCLStats/groundslothsStatsFinal.csv",
  "KCLStats/merchantsStatsFinal.csv"
)

kcl_basic_stats_dfs <- kcl_basicHitting_files |> 
  map(read_csv)

KCLBasicStats <- bind_rows(kcl_basic_stats_dfs) |> 
  filter(Name != "Total") |> 
  rename(Batter = Name)
#write_csv(KCLBasicStats, "KCLBasicStats.csv")

KCLSavantData <- kcl_advanced_by_batter |> 
  left_join(KCLBasicStats, by = "Batter")

beltersBasicStats <- read_csv("BeltersStats/beltersHittingFinal.csv")
BeltersSavantData <- belters_advanced_by_batter |> 
  left_join(beltersBasicStats, by = "Batter")

```

Function to calculate advanced reference stats (KCL)
```{r}
#Calculate League OBP and League SLG
KCLSavantData <- KCLSavantData |> 
  mutate(
    `1B` = H - `2B` - `3B` - HR,
  )

leagueSums <- KCLSavantData |> 
  summarize(pa_sum = sum(PA),
            ab_sum = sum(AB),
            bb_sum = sum(BB),
            hbp_sum = sum(HBP),
            singleSum = sum(`1B`),
            doubleSum = sum(`2B`),
            tripleSum = sum(`3B`),
            hrSum = sum(HR),
            on_base_sum = sum(H) + sum(BB) + sum(HBP),
            tb_sum = sum(TB),
            runsSum = sum(R),
            league_OBP = on_base_sum / pa_sum,
            league_SLG = tb_sum / ab_sum,
            league_wOBA = (.69*bb_sum + .72*hbp_sum + .89*singleSum + 1.27*doubleSum + 1.62*tripleSum + 2.1*hrSum) / pa_sum,
            wOBA_Scale = (.69*bb_sum + .72*hbp_sum + .89*singleSum + 1.27*doubleSum + 1.62*tripleSum + 2.1*hrSum) / runsSum,
            runsPerPA = runsSum / pa_sum
  )

leagueOBP <- leagueSums |>  pull(league_OBP)
leagueSLG <- leagueSums |>  pull(league_SLG)
leagueWOBA <- leagueSums |>  pull(league_wOBA)
wOBA_Scale <- leagueSums |> pull(wOBA_Scale)
leagueRunsPerPA <- leagueSums |> pull(runsPerPA)

#Calculate OPS+
KCLSavantData <- KCLSavantData |> 
  mutate(
    `OPS+` = round(100 * ((OBP / leagueOBP) + (SLG / leagueSLG) - 1),0)
  )


#Calculate wOBA
KCLSavantData <- KCLSavantData |> 
  mutate(
    wOBA = (.69*BB + .72*HBP + .89*`1B` + 1.27*`2B` + 1.62*`3B` + 2.1*HR) / PA
  )

#Calculate wRC+
KCLSavantData <- KCLSavantData |> 
  mutate(
    `wRC+` = round((
      ( (wOBA - leagueWOBA) / wOBA_Scale + leagueRunsPerPA ) / leagueRunsPerPA
    ) * 100,0)
  )

runsPerWin <- 11

#Calculate Offensive WAR
KCLSavantData <- KCLSavantData |> 
  mutate(
    wRAA = (wOBA - leagueWOBA) / wOBA_Scale * PA,
    rRAA = (.252 - leagueWOBA) / wOBA_Scale * PA,
    oRAR = wRAA - rRAA,
    oWAR = oRAR / runsPerWin
  )

#Select Columns We Need
KCLSavantData <- KCLSavantData |> 
  select(-`1B`, -wRAA, -rRAA, -oRAR) |> 
  mutate(
    wOBA = round(wOBA,3),
    oWAR = round(oWAR, 1)
  )


```

Function to calculate advanced reference stats (Belters)
```{r}
#Calculate League OBP and League SLG
BeltersSavantData <- BeltersSavantData |> 
  mutate(
    `1B` = H - `2B` - `3B` - HR,
    TB = `1B` + (2 * `2B`) + (3 * `3B`) + (4*HR)
  )

leagueSums <- BeltersSavantData |> 
  summarize(pa_sum = sum(PA),
            ab_sum = sum(AB),
            bb_sum = sum(BB),
            hbp_sum = sum(HBP),
            singleSum = sum(`1B`),
            doubleSum = sum(`2B`),
            tripleSum = sum(`3B`),
            hrSum = sum(HR),
            on_base_sum = sum(H) + sum(BB) + sum(HBP),
            tb_sum = sum(TB),
            runsSum = sum(RBI) + 12, #CHANGE FREQUENTLY
            league_OBP = on_base_sum / pa_sum,
            league_SLG = tb_sum / ab_sum,
            league_wOBA = (.69*bb_sum + .72*hbp_sum + .89*singleSum + 1.27*doubleSum + 1.62*tripleSum + 2.1*hrSum) / pa_sum,
            wOBA_Scale = (.69*bb_sum + .72*hbp_sum + .89*singleSum + 1.27*doubleSum + 1.62*tripleSum + 2.1*hrSum) / runsSum,
            runsPerPA = runsSum / pa_sum
  )

leagueOBP <- leagueSums |>  pull(league_OBP)
leagueSLG <- leagueSums |>  pull(league_SLG)
leagueWOBA <- leagueSums |>  pull(league_wOBA)
wOBA_Scale <- leagueSums |> pull(wOBA_Scale)
leagueRunsPerPA <- leagueSums |> pull(runsPerPA)

#Calculate OPS+
BeltersSavantData <- BeltersSavantData |> 
  mutate(
    `OPS+` = round(100 * ((OBP / leagueOBP) + (SLG / leagueSLG) - 1),0)
  )


#Calculate wOBA
BeltersSavantData <- BeltersSavantData |> 
  mutate(
    wOBA = (.69*BB + .72*HBP + .89*`1B` + 1.27*`2B` + 1.62*`3B` + 2.1*HR) / PA
  )

#Calculate wRC+
BeltersSavantData <- BeltersSavantData |> 
  mutate(
    `wRC+` = round((
      ( (wOBA - leagueWOBA) / wOBA_Scale + leagueRunsPerPA ) / leagueRunsPerPA
    ) * 100,0)
  )

runsPerWin <- 11

#Calculate Offensive WAR
BeltersSavantData <- BeltersSavantData |> 
  mutate(
    wRAA = (wOBA - leagueWOBA) / wOBA_Scale * PA,
    rRAA = (.252 - leagueWOBA) / wOBA_Scale * PA,
    oRAR = wRAA - rRAA,
    oWAR = oRAR / runsPerWin
  )

#Select Columns We Need
BeltersSavantData <- BeltersSavantData |> 
  select(-`1B`, -wRAA, -rRAA, -oRAR) |> 
  mutate(
    wOBA = round(wOBA,3),
    oWAR = round(oWAR, 1)
  )


```



Put in new xWOBA
```{r}
#Fix xWOBA file player names
corrections <- c(
  "Justin Trusner" = "Jacob Trusner",
  "Brooks Neuhof" = "Brooks Neuhoff",
  "Teagan Disharoom" = 	"Teagan Disharoon",
  "Kam  Ross" = "Kam Ross",
  "Brayden  Windy" = "Brayden Windy",
  "Sammy Descarpentrie" = "Sam DesCarpentrie",
  "Kannan Kleine" = "Kannon Kleine",
  "Nolan Mccrossin" = "Nolan McCrossin",
  "Luke Mcclure" = "Luke McClure",
  "Brandown Ward" = "Brandon Ward",
  "Cameron Heinold" = "Camden Heinold",
  "Sammy Driscoll" = "Sam Driscoll",
  "Roy Rolston" = "Roy Ralston",
  "Tyson Sorenson" = "Tysen Sorenson",
  "Chase Peterson" = "Chase Petersen"
)

fixNames <- function(df, column, lookup){
  old_values <- df[[column]]
  needs_fix <- old_values %in% names(lookup)
  df[[column]] <- ifelse(
    needs_fix,
    lookup[old_values],
    old_values
  )
  return(df)
}

xWOBA_2 <- read_csv("YakkertechData/xWOBA_KCL/Hitter_XWOBA.csv") |> 
  select(Batter, xWOBA, Percentile) |> 
  rename(xWOBA_2 = xWOBA,
         xWOBA_2_pct = Percentile)

#xWOBA_2 <- fixNames(xWOBA_2, "Batter", corrections)

KCLSavantData <- KCLSavantData |> 
  left_join(xWOBA_2, by = "Batter")

xWOBA_2 <- read_csv("YakkertechData/xWOBA_CornBelters/xWOBA_Data_Belters.csv") |> 
  select(Batter, xWOBA, Percentile) |> 
  rename(xWOBA_2 = xWOBA,
         xWOBA_2_pct = Percentile)

#xWOBA_2 <- fixNames(xWOBA_2, "Batter", corrections)

BeltersSavantData <- BeltersSavantData |> 
  left_join(xWOBA_2, by = "Batter")
```
Create Leaderboards
```{r}
# basicLeaderboard <- KCLSavantData |> 
#   select(Batter, PA, AB, H, `2B`, `3B`, HR, SB, AVG, OBP, SLG, OPS, wOBA, `wRC+`, oWAR)
# 
# advancedLeaderboard <- KCLSavantData |> 
#   select(Batter, PA, avgExitVelo, maxExitVelo, LASweetSpot, hardHitPct, squaredUpPct, kPct, bbPct, whiffPct, chasePct,
#          xBA, xSLG, xWOBA, xBABIP)
# 
# 
# 

```



Save Savant Data
```{r}
savantData <- bind_rows(KCLSavantData, BeltersSavantData)
write_csv(KCLSavantData, "KCLHitterSavantData.csv")
write_csv(BeltersSavantData, "BeltersHitterSavantData.csv")
write_csv(savantData, "HitterSavantData.csv")
```


```{r}
yakkertechData |> 
  filter(!is.na(RelSpeed)) |> 
  filter(PitcherTeam == "Kcl merchants 2025" | PitcherTeam == "Kcl bobcats 2025" | PitcherTeam == "Kcl bluecaps 2025" | PitcherTeam == "Kcl groundsloths 2025") |> 
  select(Date, PitcherTeam, Pitcher, RelSpeed) |> 
  rename("PitchSpeed" = "RelSpeed") |> 
  arrange(desc(PitchSpeed))
```


```{r}
test <- yakkertechData |> 
  filter(Batter == "Jake Parpet") |> 
  filter(!is.na(PlayResult)) |> 
  summarise(mean = mean(predicted_xwoba))
```






